In [1]:
# Application: Student Exam Pass/Fail Analysis
import numpy as np
from scipy.stats import bernoulli, binom

# BERNOULLI DISTRIBUTION
print("----- Bernoulli Distribution -----")
# Probability of passing an exam
p = 0.7
# Generate 10 random student outcomes
# 1 = Pass, 0 = Fail
bernoulli_samples = bernoulli.rvs(p, size=10)
print("Probability of Passing:", p)
print("Student Outcomes (1=Pass, 0=Fail):")
print(bernoulli_samples)
# Probability of success and failure
print("\nProbability of Pass:")
print(bernoulli.pmf(1, p))
print("Probability of Fail:")
print(bernoulli.pmf(0, p))


----- Bernoulli Distribution -----
Probability of Passing: 0.7
Student Outcomes (1=Pass, 0=Fail):
[1 1 1 1 1 1 1 1 1 1]

Probability of Pass:
0.7
Probability of Fail:
0.30000000000000004


In [2]:
# Statistical Hypothesis Testing
# 1. Z-Test
# 2. Independent t-Test
# Application: Student Performance Analysis
import numpy as np
from scipy import stats
from statsmodels.stats.weightstats import ztest

# Z-TEST
print("----- Z-Test -----")
# Sample marks of students
sample_marks = np.array([78, 82, 85, 88, 90, 76, 95, 89, 84, 91])
# Population mean
population_mean = 80
# Perform one-sample Z-test
z_stat, p_value = ztest(sample_marks, value=population_mean)
print("Sample Marks:")
print(sample_marks)
print("\nPopulation Mean:", population_mean)
print("\nZ-Statistic:", z_stat)
print("P-Value:", p_value)
# Decision
alpha = 0.05
if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")
# INDEPENDENT t-TEST
print("\n\n----- Independent t-Test -----")
# Marks of two different classes
class_A = np.array([78, 82, 85, 88, 90])
class_B = np.array([72, 75, 70, 68, 74])
# Perform independent t-test
t_stat, p_value = stats.ttest_ind(class_A, class_B)
print("Class A Marks:")
print(class_A)
print("\nClass B Marks:")
print(class_B)
print("\nt-Statistic:", t_stat)
print("P-Value:", p_value)
# Decision
if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")



----- Z-Test -----
Sample Marks:
[78 82 85 88 90 76 95 89 84 91]

Population Mean: 80

Z-Statistic: 3.0778387488959273
P-Value: 0.0020850770735042832

Result: Reject Null Hypothesis


----- Independent t-Test -----
Class A Marks:
[78 82 85 88 90]

Class B Marks:
[72 75 70 68 74]

t-Statistic: 5.140603704975992
P-Value: 0.000884475345807384

Result: Reject Null Hypothesis
